### PR TITLE
Show all IP from a node

### PR DESCRIPTION
**Pull request by danieltolmon**
enhancement #12 

Added a new column with IP

Screenshot 2019-12-16 at 18 12 19

When the user press the link 'Show IP', it appears a modal showing the IPs related to this node (a call to /api/2.0/nodes/:nodeId/catalogs is made in order to get the IPs)

Screenshot 2019-12-16 at 18 15 38

Note: Only compute nodes have IPs.
Note 2: All the computes nodes have an IP and other IP with 0.0.0.0 (Do I have to show this 0.0.0.0 IP or not?)

### CODE REVIEW

**Comment by danielgek** [comment]
LGTM but your question needs to be answered by @jsaguiar i think

**Comment by jsaguiar** [comment]
please ignore 0.0.0.0 ips

**Comment by danielgek** [comment]
LGTM 🔥

**Comment by danielgek** [comment]
@danieltolmon if it's ready feature wise, let's merge it

**Pull request merged**
